import os
import json
import re
import shutil
import zipfile
import mammoth
import io
from datetime import datetime

from fastapi import FastAPI, HTTPException, APIRouter, Request
from fastapi.responses import FileResponse, HTMLResponse, StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from docx import Document
from typing import Optional

# ==========================
# APP SETUP
# ==========================
app = FastAPI(
    title="VSM Document Management API",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

router = APIRouter()

# ==========================
# PATH CONFIG
# ─────────────────────────
# VSM_ROOT is always the folder containing THIS script.
#
# Old location: C:\Users\SarmanEngineering\Documents\vector_database\VSM
# New location: D:\vector_database\VSM
#
# Since vsm_root is derived from __file__, it automatically points
# to wherever this script lives. No hardcoded paths anywhere.
#
# central_index.json now stores RELATIVE paths (generated by the
# updated generate_index.py), so the server resolves them at runtime:
#     absolute_path = vsm_root + "/" + relative_path_from_json
#
# Moving to a new drive = just re-run generate_index.py once.
# ==========================
VSM_ROOT        = os.path.dirname(os.path.abspath(__file__))
CENTRAL_JSON    = os.path.join(VSM_ROOT, "central_index.json")
WORKING_COPIES  = os.path.join(VSM_ROOT, "Working_Copies")
VSM_DATA_FOLDER = os.path.join(VSM_ROOT, "vsm_data")
MASTER_DOCS     = os.path.join(VSM_ROOT, "Master_Documents")

os.makedirs(WORKING_COPIES, exist_ok=True)
os.makedirs(VSM_DATA_FOLDER, exist_ok=True)

print(f"[STARTUP] VSM Root      : {VSM_ROOT}")
print(f"[STARTUP] Master Docs   : {MASTER_DOCS}")
print(f"[STARTUP] Working Copies: {WORKING_COPIES}")

# ==========================
# NO PRE-ZIPPING AT ALL
# ─────────────────────────
# Pre-zip removed entirely — it was wasting disk space.
# Stage 2.4 folders are zipped live in-memory and streamed directly.
# Stage 1.3 is always a single file — served directly, no zip ever.
# Zero extra disk usage for downloads.
# ==========================

# ==========================
# SUPPORTED FILE TYPES
# ==========================
SUPPORTED_FILE_TYPES = {
    ".docx":   ("application/vnd.openxmlformats-officedocument.wordprocessingml.document", True),
    ".txt":    ("text/plain", True),
    ".pdf":    ("application/pdf", True),
    ".xls":    ("application/vnd.ms-excel", False),
    ".xlsx":   ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", False),
    ".sldprt": ("application/octet-stream", False),
    ".sldasm": ("application/octet-stream", False),
    ".step":   ("application/octet-stream", False),
    ".stp":    ("application/octet-stream", False),
}

FILE_PRIORITY = [".docx", ".pdf", ".txt", ".xlsx", ".xls", ".sldprt", ".sldasm", ".step", ".stp"]

# ==========================
# LOAD CENTRAL INDEX
# ==========================
if not os.path.exists(CENTRAL_JSON):
    raise FileNotFoundError(f"central_index.json missing — expected at: {CENTRAL_JSON}")

with open(CENTRAL_JSON, "r", encoding="utf-8") as f:
    central_index = json.load(f)

print(f"[STARTUP] central_index.json loaded — {len(central_index)} product type(s)")

# ==========================
# HELPERS
# ==========================
def get_file_ext(path: str) -> str:
    return os.path.splitext(path)[1].lower()

def get_mime_type(path: str) -> str:
    mime, _ = SUPPORTED_FILE_TYPES.get(get_file_ext(path), ("application/octet-stream", False))
    return mime

def is_previewable(path: str) -> bool:
    _, previewable = SUPPORTED_FILE_TYPES.get(get_file_ext(path), ("application/octet-stream", False))
    return previewable

def is_supported(path: str) -> bool:
    return get_file_ext(path) in SUPPORTED_FILE_TYPES

def resolve_path(stored_path: str) -> str:
    """
    Convert a path from central_index.json into a real absolute path.

    Handles both cases:
      1. RELATIVE path (new format): "Master_Documents/EE/.../file.docx"
         -> joins with VSM_ROOT to get absolute path on current drive
      2. ABSOLUTE path (old format): "D:\\vector_database\\VSM\\..."
         -> returned as-is (still works if files are on that drive)

    This means old central_index.json files keep working, and new ones
    are fully portable across drives.
    """
    if os.path.isabs(stored_path):
        # Old absolute path format — use directly
        return stored_path
    else:
        # New relative path format — resolve against vsm_root
        return os.path.normpath(os.path.join(VSM_ROOT, stored_path))

def pick_best_file(documents: list) -> Optional[str]:
    existing = [resolve_path(p) for p in documents if os.path.exists(resolve_path(p))]
    if not existing:
        return None
    for ext in FILE_PRIORITY:
        for p in existing:
            if get_file_ext(p) == ext:
                return p
    return existing[0]

def read_stage_explanation(stage: str) -> str:
    path = os.path.join(VSM_DATA_FOLDER, f"{stage}_explanation.docx")
    if not os.path.exists(path):
        return f"No explanation available for stage {stage}"
    doc = Document(path)
    return "\n".join(p.text for p in doc.paragraphs if p.text.strip())

def create_versioned_copy(source_path: str) -> str:
    """Copy a single file into Working_Copies with a version suffix."""
    date_folder = os.path.join(WORKING_COPIES, datetime.now().strftime("%Y-%m-%d"))
    os.makedirs(date_folder, exist_ok=True)
    base = os.path.basename(source_path)
    name, ext = os.path.splitext(base)
    version = 1
    while True:
        dest = os.path.join(date_folder, f"{name}_v{version}{ext}")
        if not os.path.exists(dest):
            break
        version += 1
    shutil.copy2(source_path, dest)
    return dest

def _norm(text: str) -> str:
    return re.sub(r"[\s\-_]+", "_", text.strip().upper())

# ==========================
# IN-MEMORY ZIP STREAM
# ─────────────────────────
# Used ONLY for stage 2.4 folder downloads.
# Entire zip is built in RAM and streamed in 1MB chunks.
# Nothing written to disk — zero disk usage.
# ZIP_STORED used (no compression) because source files
# (.docx, .pdf, .sldprt etc.) are already compressed formats.
# ==========================
def zip_folder_stream(folder_path: str):
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_STORED) as zf:
        for root, dirs, files in os.walk(folder_path):
            for fname in files:
                fpath   = os.path.join(root, fname)
                arcname = os.path.relpath(fpath, folder_path)
                zf.write(fpath, arcname=arcname)
    buffer.seek(0)
    while True:
        chunk = buffer.read(1024 * 1024)  # 1MB chunks
        if not chunk:
            break
        yield chunk

# ==========================
# QUERY PARSER
# ==========================
def extract_stage(text: str) -> Optional[str]:
    m = re.search(r"\b(\d+\.\d+)\b", text)
    return m.group(1) if m else None

def find_variant(query: str):
    """
    Match the query to a variant using TOKEN OVERLAP SCORING.

    OLD approach (broken):
        if _norm(variant) in _norm(query)  ← "C" matches inside "TR_3PH_CS_01_6V_2000A"

    NEW approach (correct):
        Split both variant and query into tokens, count how many match.
        Pick the variant with the HIGHEST score and at least 2 tokens matched.
        Short/ambiguous variants like "C" will always lose to the real full code.

    Example:
        query   = "TR_3PH_CS_01_6V_2000A 1.3"
        tokens  = {"TR", "3PH", "CS", "01", "6V", "2000A"}

        variant "C"                    → score 0  (no token overlap)
        variant "TR_3PH_CS_01_6V_2000A" → score 6  (wins correctly)
    """
    query_tokens = set(_norm(query).split("_"))
    # Remove pure stage-number tokens like "1" "3" "1.3" from scoring
    query_tokens = {t for t in query_tokens if not re.match(r"^\d+(\.\d+)?$", t)}

    best_score   = 0
    best_variant = None
    best_ptype   = None

    for ptype, pdata in central_index.items():
        for v in pdata.get("variants", {}):
            variant_tokens = set(_norm(v).split("_"))
            score = len(variant_tokens & query_tokens)
            if score > best_score:
                best_score   = score
                best_variant = v
                best_ptype   = ptype

    # Require at least 2 tokens to match — prevents single-letter variants
    # like "C" from ever winning
    if best_score >= 2:
        return best_ptype, best_variant

    return None, None

# ==========================
# REQUEST MODEL
# ==========================
class QueryRequest(BaseModel):
    query: str

# ==========================
# QUERY ENDPOINT
# ==========================
@router.post("/query")
def process_query(req: QueryRequest, request: Request):

    user_input = req.query.strip()
    stage      = extract_stage(user_input)

    if not stage:
        raise HTTPException(
            status_code=400,
            detail=(
                "Could not find a stage number in your query. "
                "Try: '1.3 for EE_01_03_10-400A_440-440V' or '2.4 Linear Fixture Pneumatic'"
            )
        )

    product_type, variant_code = find_variant(user_input)

    if not variant_code:
        all_variants = [
            vk
            for pd in central_index.values()
            for vk in pd.get("variants", {}).keys()
        ]
        raise HTTPException(
            status_code=404,
            detail=(
                f"Could not match any product from your query '{user_input}'. "
                f"Known products: {all_variants}"
            )
        )

    explanation = read_stage_explanation(stage)

    # ==========================
    # STEP 1 — Scan Master_Documents for best matching item
    # ─────────────────────────────────────────────────────
    # Stage 1.3 → always a single file  → serve directly (NO zip)
    # Stage 2.4 → can be a folder       → stream as in-memory zip
    # Any stage → single file match     → serve directly (NO zip)
    # ==========================
    product_root = os.path.join(MASTER_DOCS, product_type)
    variant_root = None

    if os.path.exists(product_root):
        for folder in os.listdir(product_root):
            if _norm(folder) == _norm(variant_code):
                variant_root = os.path.join(product_root, folder)
                break

    if variant_root and os.path.isdir(variant_root):

        query_tokens = set(_norm(user_input).split("_"))
        query_tokens = {t for t in query_tokens if not re.match(r"^\d+\.\d+$", t)}

        best_match = None
        best_score = 0

        for item in os.listdir(variant_root):
            item_path = os.path.join(variant_root, item)
            tokens    = set(_norm(item).split("_"))
            score     = len(tokens & query_tokens)
            if score > best_score:
                best_score = score
                best_match = (item, item_path)

        if best_match and best_score >= 2:
            item_name, item_path = best_match

            # ── FOLDER match → only valid for stage 2.4 ──
            if os.path.isdir(item_path):
                if stage == "2.4":
                    # Return download_url just like stage 1.3.
                    # Flutter opens this in the browser → browser auto-downloads the zip.
                    # The /vsm/download_zip/ endpoint streams it live from memory.
                    safe_name    = re.sub(r"[^\w\-.]", "_", item_name)
                    from urllib.parse import quote
                    encoded_path = quote(item_path.replace("\\", "/"), safe=":/")
                    print(f"  [2.4] Returning download_url for zip: {safe_name}")
                    return {
                        "stage":              stage,
                        "product_code":       variant_code,
                        "matched_from_query": user_input,
                        "explanation":        explanation,
                        "download_url":       f"/download_zip/?folder_path={encoded_path}&zip_name={safe_name}",
                        "preview_url":        "",
                        "file_type":          ".zip",
                        "entry_type":         "folder_zip",
                    }
                else:
                    return {
                        "stage":        stage,
                        "product_code": variant_code,
                        "explanation":  explanation,
                        "error":        f"Stage {stage} matched a folder — only stage 2.4 supports folder downloads.",
                        "download_url": "",
                        "preview_url":  "",
                    }

            # ── FILE match → serve directly, no zip ──
            # This is the normal path for stage 1.3 (single .docx/.pdf)
            if os.path.isfile(item_path) and is_supported(item_path):
                working_path  = create_versioned_copy(item_path)
                relative_path = os.path.relpath(working_path, WORKING_COPIES).replace("\\", "/")
                ext           = get_file_ext(item_path)
                return {
                    "stage":              stage,
                    "product_code":       variant_code,
                    "matched_from_query": user_input,
                    "explanation":        explanation,
                    "download_url":       f"/download_doc/?relative_path={relative_path}",
                    "preview_url":        (
                        f"/view_doc/?relative_path={relative_path}"
                        if is_previewable(item_path) else ""
                    ),
                    "file_type":  ext,
                    "entry_type": "file",
                }

    # ==========================
    # STEP 2 — Fallback: central_index lookup
    # resolve_path() handles both old absolute paths and new relative paths
    # ==========================
    variant_data     = central_index[product_type]["variants"].get(variant_code, {})
    available_stages = list(variant_data.keys())

    if stage not in variant_data:
        return {
            "stage":            stage,
            "product_code":     variant_code,
            "explanation":      f"Stage {stage} not available. Available: {available_stages}",
            "download_url":     "",
            "preview_url":      "",
            "available_stages": available_stages,
            "file_type":        None,
        }

    stage_data = variant_data[stage]
    docs = stage_data.get("documents", [])
    if isinstance(docs, str):
        docs = [docs]

    best_path = pick_best_file(docs)

    if not best_path:
        return {
            "stage":            stage,
            "product_code":     variant_code,
            "explanation":      explanation,
            "download_url":     "",
            "preview_url":      "",
            "available_stages": available_stages,
            "file_type":        None,
            "error":            "No files found on disk for this stage.",
        }

    if not is_supported(best_path):
        return {
            "stage":            stage,
            "product_code":     variant_code,
            "explanation":      explanation,
            "download_url":     "",
            "preview_url":      "",
            "available_stages": available_stages,
            "file_type":        get_file_ext(best_path),
            "error":            f"Unsupported file type: {get_file_ext(best_path)}",
        }

    working_path  = create_versioned_copy(best_path)
    relative_path = os.path.relpath(working_path, WORKING_COPIES).replace("\\", "/")
    ext           = get_file_ext(best_path)

    return {
        "stage":              stage,
        "product_code":       variant_code,
        "matched_from_query": user_input,
        "explanation":        explanation,
        "download_url":       f"/download_doc/?relative_path={relative_path}",
        "preview_url":        (
            f"/view_doc/?relative_path={relative_path}"
            if is_previewable(best_path) else ""
        ),
        "available_stages": available_stages,
        "file_type":        ext,
        "all_file_types":   [get_file_ext(resolve_path(p)) for p in docs if os.path.exists(resolve_path(p))],
        "entry_type":       "file",
    }


# ==========================
# RELOAD INDEX
# ==========================
@router.post("/reload")
def reload_index():
    global central_index
    if not os.path.exists(CENTRAL_JSON):
        raise HTTPException(status_code=500, detail="central_index.json missing")
    with open(CENTRAL_JSON, "r", encoding="utf-8") as f:
        central_index = json.load(f)
    return {
        "message":  "Index reloaded successfully",
        "products": len(central_index),
    }


# ==========================
# DOWNLOAD ZIP — Stage 2.4 folders
# ─────────────────────────────────
# Flutter opens this URL in the browser (same as download_url for 1.3).
# Browser hits this GET endpoint → server streams zip from memory → 
# browser automatically downloads the zip file.
# Zero disk usage — built and streamed entirely in RAM.
# ==========================
@router.get("/download_zip/")
def download_zip(folder_path: str, zip_name: str):
    # Security check:
    # folder_path must contain "Master_Documents" somewhere in it —
    # this handles cases where code runs on C: but database is on D:
    # or any other drive, without breaking the path validation.
    abs_folder = os.path.abspath(folder_path)

    # Normalize to forward slashes for consistent checking
    # This single line handles the conversion correctly
    norm_folder = abs_folder.replace("\\", "/")

    if "Master_Documents" not in norm_folder:
        raise HTTPException(status_code=403, detail="Access denied — path must be inside Master_Documents")
    if not os.path.isdir(abs_folder):
        raise HTTPException(status_code=404, detail=f"Folder not found: {abs_folder}")

    safe_name = re.sub(r"[^\w\-.]", "_", zip_name)
    print(f"  [DOWNLOAD_ZIP] Streaming zip: {safe_name}.zip  folder: {abs_folder}")

    return StreamingResponse(
        zip_folder_stream(abs_folder),
        media_type="application/zip",
        headers={
            "Content-Disposition": f"attachment; filename={safe_name}.zip",
        },
    )


# ==========================
# DOWNLOAD DOC
# ==========================
@router.get("/download_doc/")
def download_doc(relative_path: str):
    relative_path = relative_path.replace("/", os.sep).replace("\\", os.sep)
    file_path = os.path.abspath(os.path.join(WORKING_COPIES, relative_path))
    base      = os.path.abspath(WORKING_COPIES)

    if not file_path.startswith(base):
        raise HTTPException(status_code=403, detail="Access denied")
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail=f"File not found: {file_path}")

    ext  = get_file_ext(file_path)
    mime = "application/zip" if ext == ".zip" else get_mime_type(file_path)

    return FileResponse(
        path=file_path,
        filename=os.path.basename(file_path),
        media_type=mime,
    )


# ==========================
# PREVIEW DOC
# ==========================
@router.get("/view_doc/", response_class=HTMLResponse)
def view_doc(relative_path: str):
    file_path = os.path.abspath(os.path.join(WORKING_COPIES, relative_path))
    base      = os.path.abspath(WORKING_COPIES)

    if not file_path.startswith(base):
        raise HTTPException(status_code=403, detail="Access denied")
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found")

    ext = get_file_ext(file_path)

    if ext == ".docx":
        with open(file_path, "rb") as f:
            result = mammoth.convert_to_html(f)
        return f"<html><body style='font-family:Arial;padding:40px;'>{result.value}</body></html>"

    if ext == ".txt":
        with open(file_path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
        escaped = content.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return f"<html><body style='font-family:monospace;padding:40px;white-space:pre-wrap;'>{escaped}</body></html>"

    if ext == ".pdf":
        return FileResponse(
            path=file_path,
            filename=os.path.basename(file_path),
            media_type="application/pdf",
            headers={"Content-Disposition": "inline"},
        )

    raise HTTPException(
        status_code=415,
        detail=f"Preview not available for '{ext}'. Use the download URL instead.",
    )


# ==========================
# REPLACE VALUES IN DOCX
# ==========================
@router.post("/replace_values")
def replace_values(relative_path: str, replacements: dict):
    file_path = os.path.abspath(os.path.join(WORKING_COPIES, relative_path))

    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found")
    if get_file_ext(file_path) != ".docx":
        raise HTTPException(status_code=415, detail="Only .docx supported.")

    doc = Document(file_path)

    for p in doc.paragraphs:
        for run in p.runs:
            for old, new in replacements.items():
                if old in run.text:
                    run.text = run.text.replace(old, str(new))

    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                for paragraph in cell.paragraphs:
                    for run in paragraph.runs:
                        for old, new in replacements.items():
                            if old in run.text:
                                run.text = run.text.replace(old, str(new))

    doc.save(file_path)
    return {"message": "Updated successfully"}


# ==========================
# MOUNT ROUTER
# ==========================
app.include_router(router, prefix="/vsm")